# Generated by Django 4.0.4 on 2022-04-26 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_model', models.CharField(max_length=30)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='models', to='core.brand')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='models', to='core.color')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=50)),
                ('imei_1', models.CharField(max_length=15)),
                ('internal_storage', models.CharField(choices=[('32gb', '32GB'), ('2tb', '2TB'), ('4gb', '4GB'), ('64gb', '64GB'), ('1tb', '1TB'), ('8gb', '8GB'), ('256gb', '256GB'), ('128gb', '128GB'), ('512gb', '512GB'), ('16gb', '16GB')], max_length=5)),
                ('device_models', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='core.devicemodel')),
            ],
        ),
    ]
